# Generated by Django 3.1.7 on 2021-04-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210205_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='product',
        ),
    ]
