# Generated by Django 3.1.7 on 2021-04-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produto_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.produto'),
        ),
    ]
