# Generated by Django 3.1.7 on 2021-04-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210402_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtag', models.CharField(max_length=50)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tags')),
            ],
        ),
    ]
